openapi: 3.0.0

info:
  title: Azure Resource Graph
  description: Azure Resource Graph API Reference
  version: '2024-04-01'

servers:
  - url: https://management.azure.com/
paths:
  /providers/Microsoft.ResourceGraph/resources?api-version=2024-04-01:
    post:        
      operationId: ARG_GetAttackPath
      parameters:
        - in: query 
          name: api-version
          schema:
              type: string
              default: '2024-04-01'
          required: true              
      requestBody:              
        description: A KQL query        
        required: true                  
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  required: true   
      responses:
        '200':
          description: Result of the query operation
